# Generated by Django 5.2.2 on 2025-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/task/'),
        ),
    ]
