# Generated by Django 5.2.2 on 2025-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_duedate_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(upload_to='uploads/task/'),
        ),
    ]
