# Generated by Django 5.2.2 on 2025-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
