# Generated by Django 5.2.2 on 2025-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=3),
        ),
    ]
