# Generated by Django 5.2.2 on 2025-06-22 11:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
